//! RunaDB Wire Protocol — shared message type definitions.
//! Used by both RunaDB Server (src/net/runadb.zig) and RunaDB Client (clint/).
//! Version: v3.0 (development contract; incompatible with the retired SQL endpoint).

/// The major version negotiated in HELLO. A peer whose major differs is
/// rejected with HELLO_ERROR before any v3-only framing is parsed, so a v2
/// peer can never misparse the trailing credential that v3 HELLO_OK appends.
pub const PROTOCOL_VERSION_MAJOR: u16 = 3;
pub const PROTOCOL_VERSION_MINOR: u16 = 0;
pub const IR_FORMAT_VERSION: u16 = 4;

/// HELLO_OK (server -> client) layout — the shared parsing contract. The body
/// is a length-prefixed server version string, then exactly
/// CANCEL_CREDENTIAL_LENGTH bytes of cancellation credential, in that order
/// with nothing after. The Server writes them in this order (sendHelloOk in
/// src/net/runadb.zig) and the Client reads them in this order (readMessage in
/// clint/zig/codec.zig), so both must change together if this layout does.

/// Message type identifiers.
pub const Type = enum(u8) {
    /// Client → Server: initiates connection, carries protocol version.
    hello = 0x01,
    /// Server → Client: accepts connection; carries the server version string
    /// followed by the Connection's CANCEL_CREDENTIAL_LENGTH-byte credential.
    hello_ok = 0x02,
    /// Server → Client: rejects connection with a reason.
    hello_error = 0x03,

    /// Client → Server: submits Runa Flow source for parse, binding, and execution.
    flow_source = 0x10,
    /// Client → Server: submits canonical Runa Query IR.
    flow_ir = 0x15,
    /// Server → Client: column metadata for result rows.
    row_description = 0x11,
    /// Server → Client: a single row of data.
    row_data = 0x12,
    /// Server → Client: statement finished successfully.
    command_complete = 0x13,
    /// Server → Client: statement failed.
    server_error = 0x14,

    /// Client -> Server attachment staging for an `observe` IR request.
    attachment_begin = 0x20,
    attachment_chunk = 0x21,
    attachment_finish = 0x22,
    attachment_abort = 0x23,

    /// Server -> Client bounded payload stream for `read_evidence_payload`.
    payload_begin = 0x28,
    payload_chunk = 0x29,
    payload_finish = 0x2A,

    /// Client -> Server: requests cooperative cancellation of the statement
    /// currently executing on the Connection named by the credential.
    /// Fire-and-forget: the Server never replies to a well-formed request.
    /// Unknown, mismatched, closed, or expired credentials finish as a no-op.
    /// A malformed payload is a protocol error: the Server replies with CN1001
    /// and closes the Connection.
    cancel_request = 0x30,

    /// Either side: clean close.
    goodbye = 0xFF,

    _,
};

// ── Message payload structures ──

/// Payload of hello (client → server).
pub const Hello = packed struct {
    version_major: u16,
    version_minor: u16,
};

/// Payload of hello_ok (server → client).
/// Followed by a length-prefixed server version string.
/// Payload of hello_error (server → client).
/// Followed by a length-prefixed reason string.
/// Payload of flow_source (client → server).
/// Followed by a length-prefixed Runa Flow source string.
///
/// Payload of flow_ir (client → server).
/// `u16` big-endian IR format version followed by canonical IR bytes.
/// Payload of row_description (server → client).
pub const RowDescription = packed struct {
    column_count: u16,
};
/// For each column, a length-prefixed name string follows.
/// Payload of row_data (server → client).
pub const RowData = packed struct {
    column_count: u16,
};
/// For each column, a null flag (u8, 0=not null, 1=null) followed by a
/// length-prefixed text value (omitted if null).
/// Payload of command_complete (server → client).
/// Followed by a length-prefixed tag string (e.g. "INSERT 0 1", "SELECT 3").
pub const CommandComplete = packed struct {
    affected_rows: u64,
};

/// Payload of error (server → client).
/// Followed by severity byte, then length-prefixed code and message strings.
pub const Error = packed struct {
    severity: u8, // 0=INFO, 1=WARNING, 2=ERROR, 3=FATAL
};

/// Payload of goodbye (either side).
/// Followed by a length-prefixed reason string.

// ── Wire format helpers ──

/// Maximum message body length (1 MB).
pub const MAX_BODY_LENGTH: usize = 1024 * 1024;

/// Minimum header size: 4-byte length + 1-byte type.
pub const HEADER_SIZE: usize = 5;

/// String on the wire: u32 (big-endian length) + UTF-8 bytes.
pub const MAX_STRING_LENGTH: usize = 64 * 1024;

pub const MAX_ATTACHMENT_LENGTH: usize = 8 * 1024 * 1024;

/// Payload of cancel_request: an unpredictable credential unique within the
/// Connection lifetime, generated by the Server after startup and delivered to
/// the client in the HELLO_OK response.
pub const CANCEL_CREDENTIAL_LENGTH: usize = 16;
pub const MAX_ATTACHMENT_CHUNK_LENGTH: usize = 256 * 1024;
pub const PAYLOAD_DIGEST_LENGTH: usize = 32;

pub const Modality = enum(u8) {
    text = 1,
    image = 2,
    audio = 3,
    video = 4,
    sensor = 5,
    other = 6,
};

/// A scalar value for a document field in the official RunaDB Client. Text is
/// borrowed by the caller and owned by it for the duration of the request.
pub const DocumentValue = union(enum) {
    null,
    int: i64,
    text: []const u8,
    bool: bool,
};

/// One field of a `document_insert` request. `path` is a dotted path (for
/// example `author.name`).
pub const DocumentField = struct {
    path: []const u8,
    value: DocumentValue,
};
